### ISSUE TITLE
World is buggy in Jupyter. 

### ISSUE THREAD

**Issue by depaoli9** [DCC-Lab/PyTissueOptics#10]
Hopefully you can see the issue in the pdf. 

Trying to run the __main__ script in Jupyter more than once causes some weird duplication issues. If I set World to None and then re-run it also will not work until I re-import.

[20210305_PyTissueOpticsTest.pdf](https://github.com/DCC-Lab/PyTissueOptics/files/6093448/20210305_PyTissueOpticsTest.pdf)

**Comment by PyMarc2** [comment]
interesting. I don't work with jupyter notebook usually. I'll take a look. I believe it is because jupyter stores all the info of the kernel and never deletes it. The code was truly made in a .py lauchable manner I believe. Maybe adding object deletion at the end of a simulation would give the ability to relauch the code. I'll try some things over the weekend.

**Comment by dccote** [comment]
Why do you set `World` to None? You can't do that.   `World` is a class and setting it to None simply "erases" the class. 
I guess that all the variables are kept in memory and the second run is problematic?  `World` may have more than one object.  Let me try to fix this for you with a `reset()` function.

**Comment by dccote** [comment]
I am in fact quite sure this is what is going on: by running the code twice, in Jupyter, then you end up adding the objects twice (or three times etc...) because the objects are kept in a class variable (`World.geometries`) same with laser sources (`World.sources`).

If you want to test, write this before running again instead of setting `World` to None.  I am sure this will work:
```
World.geometries = set()
World.sources = set()
```

**Comment by dccote** [comment]
The reason I use `World` as a class with only `classmethods` is that I thought this was simpler.  However, that brings problems to Jupyter because `World` is not an instance, it is just a class with class properties, and they survive from one run to the other.  In Jupyter, that's bad because it keeps everything in memory. That can be solved easily by modiyfing the design to instantiate `world = World()` at the beginning and then work with a clean world.  Anyway, if I don't do that, I will have to call `World.reset()` which is even worse in terms of simplicity.
